# Uncomment the next line to define a global platform for your project
platform :ios, '15.5'

target 'DeviceSenseCocoaPodsDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!

  pod 'StreambirdDeviceSense', :git => 'https://github.com/streambird/streambird-devicesense.git'

end